# API Skateshop - Produk Saja (localhost)
@baseUrl = https://skateshop-backend-663618957788.asia-southeast1.run.app


### Dapatkan Semua Produk (Publik)
GET {{baseUrl}}/products

### Filter Produk berdasarkan Kategori (Publik)
GET {{baseUrl}}/products?category=deck

### Dapatkan Produk berdasarkan ID (Publik)
GET {{baseUrl}}/products/1

### Buat Produk Baru
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Element Skateboard Deck",
    "description": "Deck kayu maple 7-ply berkualitas tinggi dari Element",
    "category": "deck",
    "price": 750000,
    "imageUrl": "element-deck.jpg"
}

### Update Produk
PUT {{baseUrl}}/products/1
Content-Type: application/json

{
    "name": "Santa Skateboard Deck Pro",
    "category": "deck",
    "price": 800000,
    "imageUrl": "https://nhsskatedirect.com/cdn/shop/files/79688_1800x.jpg?v=1749189831"
}

### Hapus Produk
DELETE {{baseUrl}}/products/1